// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

module routeguide.route_guide;

import google.protobuf;

enum protocVersion = 3012003;

class Point
{
    @Proto(1) int latitude = protoDefaultValue!int;
    @Proto(2) int longitude = protoDefaultValue!int;
}

class Rectangle
{
    @Proto(1) Point lo = protoDefaultValue!Point;
    @Proto(2) Point hi = protoDefaultValue!Point;
}

class Feature
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) Point location = protoDefaultValue!Point;
}

class RouteNote
{
    @Proto(1) Point location = protoDefaultValue!Point;
    @Proto(2) string message = protoDefaultValue!string;
}

class RouteSummary
{
    @Proto(1) int pointCount = protoDefaultValue!int;
    @Proto(2) int featureCount = protoDefaultValue!int;
    @Proto(3) int distance = protoDefaultValue!int;
    @Proto(4) int elapsedTime = protoDefaultValue!int;
}
