name: CI
on: [push, pull_request]
jobs:
  test:
    name: unittests
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub -q test
